/**
 * TrainingApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/KeyPairModel'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./KeyPairModel'));
  } else {
    // Browser globals (root is window)
    if (!root.TrainingApi) {
      root.TrainingApi = {};
    }
    root.TrainingApi.ApiKeysModel = factory(root.TrainingApi.ApiClient, root.TrainingApi.KeyPairModel);
  }
}(this, function(ApiClient, KeyPairModel) {
  'use strict';




  /**
   * The ApiKeysModel model module.
   * @module model/ApiKeysModel
   * @version 1.0
   */

  /**
   * Constructs a new <code>ApiKeysModel</code>.
   * @alias module:model/ApiKeysModel
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ApiKeysModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApiKeysModel} obj Optional instance to populate.
   * @return {module:model/ApiKeysModel} The populated <code>ApiKeysModel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('TrainingKeys')) {
        obj['TrainingKeys'] = KeyPairModel.constructFromObject(data['TrainingKeys']);
      }
      if (data.hasOwnProperty('PredictionKeys')) {
        obj['PredictionKeys'] = KeyPairModel.constructFromObject(data['PredictionKeys']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/KeyPairModel} TrainingKeys
   */
  exports.prototype['TrainingKeys'] = undefined;
  /**
   * @member {module:model/KeyPairModel} PredictionKeys
   */
  exports.prototype['PredictionKeys'] = undefined;



  return exports;
}));


