/**
 * TrainingApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TrainingApi) {
      root.TrainingApi = {};
    }
    root.TrainingApi.ImageTagModel = factory(root.TrainingApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ImageTagModel model module.
   * @module model/ImageTagModel
   * @version 1.0
   */

  /**
   * Constructs a new <code>ImageTagModel</code>.
   * Represents a Tag
   * @alias module:model/ImageTagModel
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>ImageTagModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ImageTagModel} obj Optional instance to populate.
   * @return {module:model/ImageTagModel} The populated <code>ImageTagModel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Id')) {
        obj['Id'] = ApiClient.convertToType(data['Id'], 'String');
      }
      if (data.hasOwnProperty('Name')) {
        obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
      }
      if (data.hasOwnProperty('Description')) {
        obj['Description'] = ApiClient.convertToType(data['Description'], 'String');
      }
      if (data.hasOwnProperty('ImageCount')) {
        obj['ImageCount'] = ApiClient.convertToType(data['ImageCount'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Gets the Tag ID
   * @member {String} Id
   */
  exports.prototype['Id'] = undefined;
  /**
   * Gets or sets the name of the tag
   * @member {String} Name
   */
  exports.prototype['Name'] = undefined;
  /**
   * Gets or sets the description of the tag
   * @member {String} Description
   */
  exports.prototype['Description'] = undefined;
  /**
   * Gets the number of images labelled with this tag
   * @member {Number} ImageCount
   */
  exports.prototype['ImageCount'] = undefined;



  return exports;
}));


