/**
 * TrainingApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TrainingApi) {
      root.TrainingApi = {};
    }
    root.TrainingApi.ImageTagPerformanceModel = factory(root.TrainingApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ImageTagPerformanceModel model module.
   * @module model/ImageTagPerformanceModel
   * @version 1.0
   */

  /**
   * Constructs a new <code>ImageTagPerformanceModel</code>.
   * Represents performance data for a particular tag in a trained iteration
   * @alias module:model/ImageTagPerformanceModel
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>ImageTagPerformanceModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ImageTagPerformanceModel} obj Optional instance to populate.
   * @return {module:model/ImageTagPerformanceModel} The populated <code>ImageTagPerformanceModel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('TagId')) {
        obj['TagId'] = ApiClient.convertToType(data['TagId'], 'String');
      }
      if (data.hasOwnProperty('TagName')) {
        obj['TagName'] = ApiClient.convertToType(data['TagName'], 'String');
      }
      if (data.hasOwnProperty('Precision')) {
        obj['Precision'] = ApiClient.convertToType(data['Precision'], 'Number');
      }
      if (data.hasOwnProperty('PrecisionStdDeviation')) {
        obj['PrecisionStdDeviation'] = ApiClient.convertToType(data['PrecisionStdDeviation'], 'Number');
      }
      if (data.hasOwnProperty('Recall')) {
        obj['Recall'] = ApiClient.convertToType(data['Recall'], 'Number');
      }
      if (data.hasOwnProperty('RecallStdDeviation')) {
        obj['RecallStdDeviation'] = ApiClient.convertToType(data['RecallStdDeviation'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} TagId
   */
  exports.prototype['TagId'] = undefined;
  /**
   * @member {String} TagName
   */
  exports.prototype['TagName'] = undefined;
  /**
   * Gets the precision
   * @member {Number} Precision
   */
  exports.prototype['Precision'] = undefined;
  /**
   * Gets the standard deviation for the precision
   * @member {Number} PrecisionStdDeviation
   */
  exports.prototype['PrecisionStdDeviation'] = undefined;
  /**
   * Gets the recall
   * @member {Number} Recall
   */
  exports.prototype['Recall'] = undefined;
  /**
   * Gets the standard deviation for the recall
   * @member {Number} RecallStdDeviation
   */
  exports.prototype['RecallStdDeviation'] = undefined;



  return exports;
}));


