/**
 * TrainingApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TrainingApi) {
      root.TrainingApi = {};
    }
    root.TrainingApi.IterationModel = factory(root.TrainingApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The IterationModel model module.
   * @module model/IterationModel
   * @version 1.0
   */

  /**
   * Constructs a new <code>IterationModel</code>.
   * Iteration model to be sent over JSON
   * @alias module:model/IterationModel
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>IterationModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IterationModel} obj Optional instance to populate.
   * @return {module:model/IterationModel} The populated <code>IterationModel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Id')) {
        obj['Id'] = ApiClient.convertToType(data['Id'], 'String');
      }
      if (data.hasOwnProperty('Name')) {
        obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
      }
      if (data.hasOwnProperty('Status')) {
        obj['Status'] = ApiClient.convertToType(data['Status'], 'String');
      }
      if (data.hasOwnProperty('Created')) {
        obj['Created'] = ApiClient.convertToType(data['Created'], 'Date');
      }
      if (data.hasOwnProperty('LastModified')) {
        obj['LastModified'] = ApiClient.convertToType(data['LastModified'], 'Date');
      }
      if (data.hasOwnProperty('TrainedAt')) {
        obj['TrainedAt'] = ApiClient.convertToType(data['TrainedAt'], 'Date');
      }
      if (data.hasOwnProperty('IsDefault')) {
        obj['IsDefault'] = ApiClient.convertToType(data['IsDefault'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * Gets the id of the iteration
   * @member {String} Id
   */
  exports.prototype['Id'] = undefined;
  /**
   * Gets or sets the name of the iteration
   * @member {String} Name
   */
  exports.prototype['Name'] = undefined;
  /**
   * Gets the current iteration status
   * @member {String} Status
   */
  exports.prototype['Status'] = undefined;
  /**
   * Gets the time this iteration was completed
   * @member {Date} Created
   */
  exports.prototype['Created'] = undefined;
  /**
   * Gets the time this iteration was last modified
   * @member {Date} LastModified
   */
  exports.prototype['LastModified'] = undefined;
  /**
   * Gets the time this iteration was last modified
   * @member {Date} TrainedAt
   */
  exports.prototype['TrainedAt'] = undefined;
  /**
   * Gets or sets a value indicating whether the iteration is the default iteration for the project
   * @member {Boolean} IsDefault
   */
  exports.prototype['IsDefault'] = undefined;



  return exports;
}));


