/**
 * TrainingApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TrainingApi) {
      root.TrainingApi = {};
    }
    root.TrainingApi.PredictionTagModel = factory(root.TrainingApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PredictionTagModel model module.
   * @module model/PredictionTagModel
   * @version 1.0
   */

  /**
   * Constructs a new <code>PredictionTagModel</code>.
   * @alias module:model/PredictionTagModel
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>PredictionTagModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PredictionTagModel} obj Optional instance to populate.
   * @return {module:model/PredictionTagModel} The populated <code>PredictionTagModel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('TagId')) {
        obj['TagId'] = ApiClient.convertToType(data['TagId'], 'String');
      }
      if (data.hasOwnProperty('Tag')) {
        obj['Tag'] = ApiClient.convertToType(data['Tag'], 'String');
      }
      if (data.hasOwnProperty('Probability')) {
        obj['Probability'] = ApiClient.convertToType(data['Probability'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} TagId
   */
  exports.prototype['TagId'] = undefined;
  /**
   * @member {String} Tag
   */
  exports.prototype['Tag'] = undefined;
  /**
   * @member {Number} Probability
   */
  exports.prototype['Probability'] = undefined;



  return exports;
}));


