/**
 * TrainingApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TrainingApi) {
      root.TrainingApi = {};
    }
    root.TrainingApi.PredictionQueryTokenModel = factory(root.TrainingApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PredictionQueryTokenModel model module.
   * @module model/PredictionQueryTokenModel
   * @version 1.0
   */

  /**
   * Constructs a new <code>PredictionQueryTokenModel</code>.
   * @alias module:model/PredictionQueryTokenModel
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>PredictionQueryTokenModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PredictionQueryTokenModel} obj Optional instance to populate.
   * @return {module:model/PredictionQueryTokenModel} The populated <code>PredictionQueryTokenModel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Session')) {
        obj['Session'] = ApiClient.convertToType(data['Session'], 'String');
      }
      if (data.hasOwnProperty('Continuation')) {
        obj['Continuation'] = ApiClient.convertToType(data['Continuation'], 'String');
      }
      if (data.hasOwnProperty('MaxCount')) {
        obj['MaxCount'] = ApiClient.convertToType(data['MaxCount'], 'Number');
      }
      if (data.hasOwnProperty('OrderBy')) {
        obj['OrderBy'] = ApiClient.convertToType(data['OrderBy'], 'String');
      }
      if (data.hasOwnProperty('IterationId')) {
        obj['IterationId'] = ApiClient.convertToType(data['IterationId'], 'String');
      }
      if (data.hasOwnProperty('TagIds')) {
        obj['TagIds'] = ApiClient.convertToType(data['TagIds'], ['String']);
      }
      if (data.hasOwnProperty('Threshold')) {
        obj['Threshold'] = ApiClient.convertToType(data['Threshold'], 'Number');
      }
      if (data.hasOwnProperty('StartTime')) {
        obj['StartTime'] = ApiClient.convertToType(data['StartTime'], 'Date');
      }
      if (data.hasOwnProperty('EndTime')) {
        obj['EndTime'] = ApiClient.convertToType(data['EndTime'], 'Date');
      }
      if (data.hasOwnProperty('Source')) {
        obj['Source'] = ApiClient.convertToType(data['Source'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} Session
   */
  exports.prototype['Session'] = undefined;
  /**
   * @member {String} Continuation
   */
  exports.prototype['Continuation'] = undefined;
  /**
   * @member {Number} MaxCount
   */
  exports.prototype['MaxCount'] = undefined;
  /**
   * @member {module:model/PredictionQueryTokenModel.OrderByEnum} OrderBy
   */
  exports.prototype['OrderBy'] = undefined;
  /**
   * @member {String} IterationId
   */
  exports.prototype['IterationId'] = undefined;
  /**
   * @member {Array.<String>} TagIds
   */
  exports.prototype['TagIds'] = undefined;
  /**
   * @member {Number} Threshold
   */
  exports.prototype['Threshold'] = undefined;
  /**
   * @member {Date} StartTime
   */
  exports.prototype['StartTime'] = undefined;
  /**
   * @member {Date} EndTime
   */
  exports.prototype['EndTime'] = undefined;
  /**
   * @member {String} Source
   */
  exports.prototype['Source'] = undefined;


  /**
   * Allowed values for the <code>OrderBy</code> property.
   * @enum {String}
   * @readonly
   */
  exports.OrderByEnum = {
    /**
     * value: "Newest"
     * @const
     */
    "Newest": "Newest",
    /**
     * value: "Oldest"
     * @const
     */
    "Oldest": "Oldest",
    /**
     * value: "Suggested"
     * @const
     */
    "Suggested": "Suggested"  };


  return exports;
}));


