/**
 * TrainingApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PredictionTagModel'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PredictionTagModel'));
  } else {
    // Browser globals (root is window)
    if (!root.TrainingApi) {
      root.TrainingApi = {};
    }
    root.TrainingApi.PredictionModel = factory(root.TrainingApi.ApiClient, root.TrainingApi.PredictionTagModel);
  }
}(this, function(ApiClient, PredictionTagModel) {
  'use strict';




  /**
   * The PredictionModel model module.
   * @module model/PredictionModel
   * @version 1.0
   */

  /**
   * Constructs a new <code>PredictionModel</code>.
   * result of an image classification request
   * @alias module:model/PredictionModel
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>PredictionModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PredictionModel} obj Optional instance to populate.
   * @return {module:model/PredictionModel} The populated <code>PredictionModel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Id')) {
        obj['Id'] = ApiClient.convertToType(data['Id'], 'String');
      }
      if (data.hasOwnProperty('Project')) {
        obj['Project'] = ApiClient.convertToType(data['Project'], 'String');
      }
      if (data.hasOwnProperty('Iteration')) {
        obj['Iteration'] = ApiClient.convertToType(data['Iteration'], 'String');
      }
      if (data.hasOwnProperty('Created')) {
        obj['Created'] = ApiClient.convertToType(data['Created'], 'Date');
      }
      if (data.hasOwnProperty('Predictions')) {
        obj['Predictions'] = ApiClient.convertToType(data['Predictions'], [PredictionTagModel]);
      }
      if (data.hasOwnProperty('ImageUri')) {
        obj['ImageUri'] = ApiClient.convertToType(data['ImageUri'], 'String');
      }
      if (data.hasOwnProperty('ThumbnailUri')) {
        obj['ThumbnailUri'] = ApiClient.convertToType(data['ThumbnailUri'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} Id
   */
  exports.prototype['Id'] = undefined;
  /**
   * @member {String} Project
   */
  exports.prototype['Project'] = undefined;
  /**
   * @member {String} Iteration
   */
  exports.prototype['Iteration'] = undefined;
  /**
   * @member {Date} Created
   */
  exports.prototype['Created'] = undefined;
  /**
   * @member {Array.<module:model/PredictionTagModel>} Predictions
   */
  exports.prototype['Predictions'] = undefined;
  /**
   * @member {String} ImageUri
   */
  exports.prototype['ImageUri'] = undefined;
  /**
   * @member {String} ThumbnailUri
   */
  exports.prototype['ThumbnailUri'] = undefined;



  return exports;
}));


