/**
 * TrainingApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TrainingApi);
  }
}(this, function(expect, TrainingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TrainingApi.AccountModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AccountModel', function() {
    it('should create an instance of AccountModel', function() {
      // uncomment below and update the code to test AccountModel
      //var instane = new TrainingApi.AccountModel();
      //expect(instance).to.be.a(TrainingApi.AccountModel);
    });

    it('should have the property userName (base name: "UserName")', function() {
      // uncomment below and update the code to test the property userName
      //var instane = new TrainingApi.AccountModel();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "Email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new TrainingApi.AccountModel();
      //expect(instance).to.be();
    });

    it('should have the property keys (base name: "Keys")', function() {
      // uncomment below and update the code to test the property keys
      //var instane = new TrainingApi.AccountModel();
      //expect(instance).to.be();
    });

    it('should have the property quotas (base name: "Quotas")', function() {
      // uncomment below and update the code to test the property quotas
      //var instane = new TrainingApi.AccountModel();
      //expect(instance).to.be();
    });

  });

}));
