/**
 * TrainingApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TrainingApi);
  }
}(this, function(expect, TrainingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TrainingApi.AccountQuotaModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AccountQuotaModel', function() {
    it('should create an instance of AccountQuotaModel', function() {
      // uncomment below and update the code to test AccountQuotaModel
      //var instane = new TrainingApi.AccountQuotaModel();
      //expect(instance).to.be.a(TrainingApi.AccountQuotaModel);
    });

    it('should have the property tier (base name: "Tier")', function() {
      // uncomment below and update the code to test the property tier
      //var instane = new TrainingApi.AccountQuotaModel();
      //expect(instance).to.be();
    });

    it('should have the property projects (base name: "Projects")', function() {
      // uncomment below and update the code to test the property projects
      //var instane = new TrainingApi.AccountQuotaModel();
      //expect(instance).to.be();
    });

    it('should have the property predictions (base name: "Predictions")', function() {
      // uncomment below and update the code to test the property predictions
      //var instane = new TrainingApi.AccountQuotaModel();
      //expect(instance).to.be();
    });

    it('should have the property perProject (base name: "PerProject")', function() {
      // uncomment below and update the code to test the property perProject
      //var instane = new TrainingApi.AccountQuotaModel();
      //expect(instance).to.be();
    });

  });

}));
