/**
 * TrainingApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TrainingApi);
  }
}(this, function(expect, TrainingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TrainingApi.PerProjectQuotaModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PerProjectQuotaModel', function() {
    it('should create an instance of PerProjectQuotaModel', function() {
      // uncomment below and update the code to test PerProjectQuotaModel
      //var instane = new TrainingApi.PerProjectQuotaModel();
      //expect(instance).to.be.a(TrainingApi.PerProjectQuotaModel);
    });

    it('should have the property projectId (base name: "ProjectId")', function() {
      // uncomment below and update the code to test the property projectId
      //var instane = new TrainingApi.PerProjectQuotaModel();
      //expect(instance).to.be();
    });

    it('should have the property iterations (base name: "Iterations")', function() {
      // uncomment below and update the code to test the property iterations
      //var instane = new TrainingApi.PerProjectQuotaModel();
      //expect(instance).to.be();
    });

    it('should have the property images (base name: "Images")', function() {
      // uncomment below and update the code to test the property images
      //var instane = new TrainingApi.PerProjectQuotaModel();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "Tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instane = new TrainingApi.PerProjectQuotaModel();
      //expect(instance).to.be();
    });

  });

}));
