/**
 * TrainingApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AccountModel', 'model/AccountQuotaModel', 'model/ApiKeysModel', 'model/CreateImageResultModel', 'model/CreateImageSummaryModel', 'model/DomainModel', 'model/ImageIdCreateBatch', 'model/ImageLabelModel', 'model/ImageModel', 'model/ImageTagListModel', 'model/ImageTagModel', 'model/ImageTagPerformanceModel', 'model/ImageUrlCreateBatch', 'model/IterationModel', 'model/IterationPerformanceModel', 'model/KeyPairModel', 'model/PerProjectQuotaModel', 'model/PredictionModel', 'model/PredictionQueryModel', 'model/PredictionQueryTokenModel', 'model/PredictionTagModel', 'model/ProjectModel', 'model/ProjectSettingsModel', 'model/QuotaModel', 'api/DefaultApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/AccountModel'), require('./model/AccountQuotaModel'), require('./model/ApiKeysModel'), require('./model/CreateImageResultModel'), require('./model/CreateImageSummaryModel'), require('./model/DomainModel'), require('./model/ImageIdCreateBatch'), require('./model/ImageLabelModel'), require('./model/ImageModel'), require('./model/ImageTagListModel'), require('./model/ImageTagModel'), require('./model/ImageTagPerformanceModel'), require('./model/ImageUrlCreateBatch'), require('./model/IterationModel'), require('./model/IterationPerformanceModel'), require('./model/KeyPairModel'), require('./model/PerProjectQuotaModel'), require('./model/PredictionModel'), require('./model/PredictionQueryModel'), require('./model/PredictionQueryTokenModel'), require('./model/PredictionTagModel'), require('./model/ProjectModel'), require('./model/ProjectSettingsModel'), require('./model/QuotaModel'), require('./api/DefaultApi'));
  }
}(function(ApiClient, AccountModel, AccountQuotaModel, ApiKeysModel, CreateImageResultModel, CreateImageSummaryModel, DomainModel, ImageIdCreateBatch, ImageLabelModel, ImageModel, ImageTagListModel, ImageTagModel, ImageTagPerformanceModel, ImageUrlCreateBatch, IterationModel, IterationPerformanceModel, KeyPairModel, PerProjectQuotaModel, PredictionModel, PredictionQueryModel, PredictionQueryTokenModel, PredictionTagModel, ProjectModel, ProjectSettingsModel, QuotaModel, DefaultApi) {
  'use strict';

  /**
   * ERROR_UNKNOWN.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var TrainingApi = require('index'); // See note below*.
   * var xxxSvc = new TrainingApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new TrainingApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new TrainingApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new TrainingApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The AccountModel model constructor.
     * @property {module:model/AccountModel}
     */
    AccountModel: AccountModel,
    /**
     * The AccountQuotaModel model constructor.
     * @property {module:model/AccountQuotaModel}
     */
    AccountQuotaModel: AccountQuotaModel,
    /**
     * The ApiKeysModel model constructor.
     * @property {module:model/ApiKeysModel}
     */
    ApiKeysModel: ApiKeysModel,
    /**
     * The CreateImageResultModel model constructor.
     * @property {module:model/CreateImageResultModel}
     */
    CreateImageResultModel: CreateImageResultModel,
    /**
     * The CreateImageSummaryModel model constructor.
     * @property {module:model/CreateImageSummaryModel}
     */
    CreateImageSummaryModel: CreateImageSummaryModel,
    /**
     * The DomainModel model constructor.
     * @property {module:model/DomainModel}
     */
    DomainModel: DomainModel,
    /**
     * The ImageIdCreateBatch model constructor.
     * @property {module:model/ImageIdCreateBatch}
     */
    ImageIdCreateBatch: ImageIdCreateBatch,
    /**
     * The ImageLabelModel model constructor.
     * @property {module:model/ImageLabelModel}
     */
    ImageLabelModel: ImageLabelModel,
    /**
     * The ImageModel model constructor.
     * @property {module:model/ImageModel}
     */
    ImageModel: ImageModel,
    /**
     * The ImageTagListModel model constructor.
     * @property {module:model/ImageTagListModel}
     */
    ImageTagListModel: ImageTagListModel,
    /**
     * The ImageTagModel model constructor.
     * @property {module:model/ImageTagModel}
     */
    ImageTagModel: ImageTagModel,
    /**
     * The ImageTagPerformanceModel model constructor.
     * @property {module:model/ImageTagPerformanceModel}
     */
    ImageTagPerformanceModel: ImageTagPerformanceModel,
    /**
     * The ImageUrlCreateBatch model constructor.
     * @property {module:model/ImageUrlCreateBatch}
     */
    ImageUrlCreateBatch: ImageUrlCreateBatch,
    /**
     * The IterationModel model constructor.
     * @property {module:model/IterationModel}
     */
    IterationModel: IterationModel,
    /**
     * The IterationPerformanceModel model constructor.
     * @property {module:model/IterationPerformanceModel}
     */
    IterationPerformanceModel: IterationPerformanceModel,
    /**
     * The KeyPairModel model constructor.
     * @property {module:model/KeyPairModel}
     */
    KeyPairModel: KeyPairModel,
    /**
     * The PerProjectQuotaModel model constructor.
     * @property {module:model/PerProjectQuotaModel}
     */
    PerProjectQuotaModel: PerProjectQuotaModel,
    /**
     * The PredictionModel model constructor.
     * @property {module:model/PredictionModel}
     */
    PredictionModel: PredictionModel,
    /**
     * The PredictionQueryModel model constructor.
     * @property {module:model/PredictionQueryModel}
     */
    PredictionQueryModel: PredictionQueryModel,
    /**
     * The PredictionQueryTokenModel model constructor.
     * @property {module:model/PredictionQueryTokenModel}
     */
    PredictionQueryTokenModel: PredictionQueryTokenModel,
    /**
     * The PredictionTagModel model constructor.
     * @property {module:model/PredictionTagModel}
     */
    PredictionTagModel: PredictionTagModel,
    /**
     * The ProjectModel model constructor.
     * @property {module:model/ProjectModel}
     */
    ProjectModel: ProjectModel,
    /**
     * The ProjectSettingsModel model constructor.
     * @property {module:model/ProjectSettingsModel}
     */
    ProjectSettingsModel: ProjectSettingsModel,
    /**
     * The QuotaModel model constructor.
     * @property {module:model/QuotaModel}
     */
    QuotaModel: QuotaModel,
    /**
     * The DefaultApi service constructor.
     * @property {module:api/DefaultApi}
     */
    DefaultApi: DefaultApi
  };

  return exports;
}));
